blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  resources :articles do
    resources :comentarios, only: [:create, :update, :destroy]
  end
=begin
  get "/articles" index
  post "/articles" create
  delete "/articles/:id" destroy
  get "/articles/:id" show
  get "/articles/new" new
  get "/articles/:id/edit" edit
  put "/articles/:id" update
=end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

blog/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :authenticate_user!

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = current_user.comentarios.new(comentario_params)
    @comentario.article = @article

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario.article, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario.article }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario.article, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario.article }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def set_article
      #Si especifico que un recurso depende de otro (haciéndolo anidado en el archivo routes),
      #desde el controlador puedo acceder a los parámetros del recurso padre haciendo: params[nombre_del_recurso_padre:atributo]
      @article = Article.find(params[:article_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:user_id, :article_id, :body)
    end
end

blog/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

blog/app/views/comentarios/_form.html.erb
<%= form_with(model: [@article,@comentario], remote: true, html: {id: "comentarios-form", ":data-type": "json"}) do |form| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul id="caja-comentarios">
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: @comentario.body%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

blog/app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

blog/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comentario.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comentario.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comentario.body %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>